# Generated by Django 5.2.1 on 2025-10-22 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(verbose_name='توضیحات آزمون')),
                ('passing_score', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نمره قبولی')),
                ('duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت زمان (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('target_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='courses.level', verbose_name='سطح هدف')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('question_type', models.CharField(choices=[('mc', 'چند گزینه\u200cای'), ('tf', 'درست/غلط'), ('ti', 'پاسخ متنی کوتاه')], default='mc', max_length=2, verbose_name='نوع سؤال')),
                ('score_weight', models.IntegerField(default=1, verbose_name='وزن نمره')),
                ('correct_answer_text', models.TextField(blank=True, null=True, verbose_name='پاسخ صحیح متنی/بولی')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='placement.assessment', verbose_name='آزمون')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='placement.question', verbose_name='سؤال')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نمره نهایی')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام')),
                ('is_passed', models.BooleanField(default=False, verbose_name='قبولی')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='placement.assessment', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_taken', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text_answer', models.TextField(blank=True, null=True, verbose_name='پاسخ متنی کاربر')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح بود')),
                ('score_earned', models.IntegerField(default=0, verbose_name='نمره کسب شده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.question', verbose_name='سؤال')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placement.option', verbose_name='گزینه انتخابی')),
                ('user_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='placement.userassessment', verbose_name='نتیجه ارزیابی')),
            ],
            options={
                'verbose_name': 'پاسخ کاربر',
                'verbose_name_plural': 'پاسخ\u200cهای کاربران',
            },
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_option_per_question'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_assessment', 'question')},
        ),
    ]
