# Generated by Django 5.2.1 on 2025-10-14 05:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_classsession_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('payment', 'پرداخت هزینه دوره'), ('refund', 'برگشت وجه')], max_length=10, verbose_name='نوع تراکنش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش')),
                ('is_successful', models.BooleanField(default=True, verbose_name='موفقیت\u200cآمیز')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.enrollment', verbose_name='ثبت\u200cنام مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
    ]
